version: "3"

services:
    code_prometheus:
        container_name: code_prometheus
        image: prom/prometheus
        ports:
            - "${PROMETHEUS_PORT:-5000}:9090"
        restart: always

    code_grafana:
        container_name: code_grafana
        image: grafana/grafana
        ports:
            - "${GRAFANA_PORT:-5050}:3000"
        restart: always
